extent.reporter.spark.start=true
extent.reporter.spark.out=VideoConsult.html
screenshot.dir=Screenshots
screenshot.rel.path=./Screenshots/
basefolder.name=Report/PractoData
basefolder.datetimepattern=d-MM-YY HH-MM-SS
extent.reporter.spark.vieworder=DashBoard,screenshots,category,tags,test,exception,author,logs,device
systeminfo.user=LKADADAS
systeminfo.build=windows
systeminfo.AppName=Eclipse
